//--- Browser-Check --- 
var ie	=	document.all												?	true : false;    // Alle Internetexplorer
var ie4	=	(document.all			&& !document.documentElement)		?	true : false;    // Internet Explorer der vierten Generation
var ie5	=	(document.all			&& document.documentElement)		?	true : false;    //Internet Explorer ab Generation 5
var moz	=	(document.captureEvents	&& document.documentElement)		?	true : false;    // Mozilla basierte Browser wie Netscape 7
var nsc	=	(document.captureEvents	&& !document.getElementById)		?	true : false;    // Netscape Navigator der vierten Generation
var dom	=	document.getElementById										?	true : false;    // Alle Dom-fähigen Browser
var op6	=	(document.getElementById	&& !document.documentElement)	?	true : false;    // Opera 5/6 (kennt document.documentElement nicht)
var op7	=	(window.opera && /Opera( |\/)7/i.exec(navigator.userAgent))	?	true : false;    // Opera 7
var browseranalyse = "Browser-Analyse:\n";
var browsertypHTML = "<hr>Browser-Analyse:<br>";
browseranalyse += "appName: " + navigator.appName + "\n";
browsertypHTML += "<b>appName:</b> " + navigator.appName + "<br>";
browseranalyse += "userAgent: " + navigator.userAgent + "\n";
browsertypHTML += "<b>userAgent:</b> " + navigator.userAgent + "<br>";
browseranalyse += "\n";
if (nsc)    browseranalyse += "nsc: Netscape 4" + "\n"
else        browseranalyse += "nsc: false" + "\n"
if (nsc)    browsertypHTML += "<b>nsc:</b> Netscape 4" + "<br>"
if (ie)     browseranalyse += "ie: Internet Explorer (irgendeiner)" + "\n"
else        browseranalyse += "ie: false" + "\n"
if (ie)     browsertypHTML += "<b>ie:</b> Internet Explorer (irgendeiner)" + "<br>"
if (ie4)    browseranalyse += "ie4: Internet Explorer 4" + "\n"
else        browseranalyse += "ie4: false" + "\n"
if (ie4)    browsertypHTML += "<b>ie4:</b> Internet Explorer 4" + "<br>"
if (ie5)    browseranalyse += "ie5: Internet Explorer 5" + "\n"
else        browseranalyse += "ie5: false" + "\n"
if (ie5)    browsertypHTML += "<b>ie5:</b> Internet Explorer 5" + "<br>"
if (moz)    browseranalyse += "moz: Mozilla-basierend (z.B. Mozilla 1.6 o. Netscape 7)" + "\n"
else        browseranalyse += "moz: false" + "\n"
if (moz)    browsertypHTML += "<b>moz:</b> Mozilla-basierend (z.B. Mozilla 1.6 o. Netscape 7)" + "<br>"
if (op6)    browseranalyse += "op6: Opera 6" + "\n"
else        browseranalyse += "op6: false" + "\n"
if (op6)    browsertypHTML += "<b>op6:</b> Opera 6" + "<br>"
if (op7)    browseranalyse += "op7: Opera 7" + "\n"
else        browseranalyse += "op7: false" + "\n"
if (op7)    browsertypHTML += "<b>op7:</b> Opera 7" + "<br>"
if (dom)    browseranalyse += "dom: DOM wird unterstützt" + "\n"
else        browseranalyse += "dom: false" + "\n"
if (dom)    browsertypHTML += "<b>dom:</b> DOM wird unterstützt" + "<br>"
//alert(browseranalyse);