
function init() { 
	var ww = layer_dimension('tarot_layerframe');
	spreading_offset_x += ww.left;
	spreading_offset_y += ww.top;
	spreading_target_x += ww.left;
	spreading_target_y += ww.top;
	if ( screen.width < 1024 ) {
		spreading_spacer         = 4;
	}
	init_common();
	card[1][3]=300; card[1][4]=50; card[1][7]='Tageskarte';
	if ( screen.width < 1024 ) {
		deck_path   = 'http://karten.tarot-server.net/symbolon/075/';
		deck_ext    = 'gif';
		cards_width = 75;
		card[1][3]=300; card[1][4]=50;
	}
	for (var i = 0; i < card.length; ++i) {
		if ( i > 0 || card[i][3] > 0 || card[i][4] > 0 ) {
			card[i][3] += ww.left;
			card[i][4] += ww.top;
		}
	}
}
       

var titel  = new Array(78);
var ctext  = new Array(78);
var cardv  = new Array(78);
var cardn  = new Array(78);
titel[0]    = '[Title not found!]';
cardv[0]    = '0';
cardn[0]    = '0';
ctext[0]    = new Array(1);
ctext[0][0] = '[Text not found!]';
ctext[0][1] = '[Text not found!]';
titel[1]    = '* Finde Deine heutige Tageskarte *';
cardv[1]    = '1';
cardn[1]    = '1';
ctext[1]    = new Array(1);
ctext[1][0] = '[Text not found!]';
ctext[1][1] = "<p align='justify'>Hier haben Sie nun die M&oumlglichkeit, Ihre pers&oumlnliche Tageskarte des Tarot zu ziehen.</p><p align='justify'>Betrachten Sie einige Augenblicke lang die vorgegebenen Karten des H&oumlhenpriesters und lassen Sie sich von der mystischen Ausstrahlung der Darstellung verzaubern...</p><p align='justify'>Wenn Sie sich dann daf&uumlr bereit f&uumlhlen Ihre pers&oumlnliche Tageskarte zu ziehen, dann klicken Sie bitte auf die vorgegebene Karte.</p><p align='justify'>Viel Freude mit den gewonnenen Erkenntnissen!</p>";
titel[2]    = "Stier: die oder das Geliebte";
cardv[2]    = '2';
cardn[2]    = '2';
ctext[2]    = new Array(1);
ctext[2][0] = '[Text not found!]';
ctext[2][1] = 'Geniesse den heutigen Tag, mach ihn zu einer sinnlichen Erfahrung! Was immer Du heute vorhast, nimm Dir Zeit für Dich und sieh das viele Gute um Dich herum und sei dankbar dafür. Schau auf das Schöne der Welt und schenke der materiellen Welt in ihrem besten Sinn Deine ganze Aufmerksamkeit, es lohnt sich!<div class="common_author">&copy; Ingrid Zinnel</div>';
titel[3]    = 'Zwillinge: der Vermittler';
cardv[3]    = '3';
cardn[3]    = '3';
ctext[3]    = new Array(1);
ctext[3][0] = '[Text not found!]';
ctext[3][1] = 'Heute ist ein guter Tag um Dich mit der „Leichtigkeit des Seins“ anzufreunden. „Bohre“ nicht in Problemen herum, sondern vertraue Deinem gesunden Menschenverstand! Falls Du dennoch ein Problem findest, so liegt die Lösung auf der Hand und ist einfacher als Du denkst. Falls Du keines hast (auch das soll vorkommen!) dann lass es dabei und konstruiere auch  keines.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[4]    = 'Krebs: Mutter/Kind/Gefühle';
cardv[4]    = '4';
cardn[4]    = '4';
ctext[4]    = new Array(1);
ctext[4][0] = '[Text not found!]';
ctext[4][1] = 'Wie Bild und Titel der Karte schon sagen, heute geht es um Dein inneres ( oder wenn Du Mutter bist eventuell auch um Dein äusseres) Kind. Es braucht Aufmerksamkeit! Es braucht Dich! Handle heute ganz aus dem „Bauch“, ganz aus Deinem Gefühl heraus. Lass den „Kopf“ mal beiseite und spüre nach, was Du wirklich möchtest. Scheu Dich nicht, das was Du in Dir „findest“ auch dann auszudrücken, wenn es Dir unangenehm oder gar peinlich ist.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[5]    = 'Löwe: das Ego';
cardv[5]    = '5';
cardn[5]    = '5';
ctext[5]    = new Array(1);
ctext[5][0] = '[Text not found!]';
ctext[5][1] = 'Endlich darfst Du mal ganz wichtig sein! Heute ist ein guter Tag für Dich. Ein Tag an dem Du all das tun solltest, was Du schon immer tun wolltest. Lass Dich nicht von Kritik an Deinem „ach so unmöglichem Egotrip“ abbringen. Zurückhaltung ist jetzt nicht angesagt! Du wirst merken, wie viel Spass Du hast und wie lebendig und kreativ Du Dich dann fühlst. Das willst Du doch nicht mit „falscher“ Bescheidenheit aufs Spiel setzten – oder?<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[6]    = 'Jungfrau: die Dienerin';
cardv[6]    = '6';
cardn[6]    = '6';
ctext[6]    = new Array(1);
ctext[6][0] = '[Text not found!]';
ctext[6][1] = 'Vom Ego ausgesehen ist heute nicht so ganz Dein Tag. Die anstehende Aufgabe gehört nicht zu den Lieblingsaufgaben des Ichs. Dennoch kannst du erreichen mit Dir und dem heutigen Tag zufrieden zu sein. Allerdings gelingt das nur, wenn Du es schaffst nachzugeben, vernünftig zu bleiben. Fürs erste musst Du, wie man so schön sagt, die Kirche im Dorf lassen. Vergiss nicht, es gibt ein Nachgeben aus der Stärke heraus. Darum geht es heute: Beuge Dich den Umständen aus Deiner Kraft und dem bewussten Willen heraus.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[7]    = 'Waage: der Partner';
cardv[7]    = '7';
cardn[7]    = '7';
ctext[7]    = new Array(1);
ctext[7][0] = '[Text not found!]';
ctext[7][1] = 'Heute ist ein Tag zum Verlieben! Ein guter Tag um sich mit jemandem auszusöhnen. Am besten Du überlegst, was die Person, mit der Du eventuell nicht so gut klar kommst mit Dir gemein hat, in welchen Eigenschaften sie Dir ähnlich ist. Du findest heraus: „Einiges“ -„Vieles“ - „Alles“ Gut, Aufgabe gelöst! Wenn nicht, frage einen guten Freund, er kann helfen (die anderen wissen es immer!)<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[8]    = 'Skorpion: der Verführer';
cardv[8]    = '8';
cardn[8]    = '8';
ctext[8]    = new Array(1);
ctext[8][0] = '[Text not found!]';
ctext[8][1] = 'Du steckst gerade in „Teufels Küche“! Du hast Dich in etwas verrannt und suchst einen Ausweg. Wie einfach wäre es, wenn man den Teufel sofort erkennen würde, wenn es der Partner, der Chef, der Nachbar wäre. Doch leider versteckt er sich in Dir, in Deinem „Kopf“ und „macht“ Dir dort etwas „vor“. Heute ist ein guter Tag von irgendeiner Idee, einer Fixierung loszulassen—einfach so!<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[9]    = 'Schütze: der Verkünder';
cardv[9]    = '9';
cardn[9]    = '9';
ctext[9]    = new Array(1);
ctext[9][0] = '[Text not found!]';
ctext[9][1] = 'Die Umstände des heutigen Tages verlangen von Dir Grosszügigkeit, Toleranz und Offenheit.<br />Mit kleinlichen Überlegungen, Diskussionen und Ängsten kommst Du nirgends hin. Gib Dir einen Ruck und habe Vertrauen. Du hattest es einmal, erinnere Dich, welche Umstände dazu beigetragen haben und wie es sich angefühlt hat. Spüre in die Situation hinein und hole Dir das gute Gefühl zurück. Es ist nicht verloren, nur vergessen worden, transportiere es ins Heute. Vertrauen kann nicht wirklich abhanden kommen, es ist im Ursprung des Menschen angelegt.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[10]    = 'Steinbock: der Meister';
cardv[10]    = '10';
cardn[10]    = '10';
ctext[10]    = new Array(1);
ctext[10][0] = '[Text not found!]';
ctext[10][1] = 'Ist Dein Leben  wirklich so schlimm? Oder kommt es Dir nur so vor und eigentlich ist es das ganz normale Leben eines Erwachsenen, das heute auf Dich wartet. Ja, Du trägst Verantwortung! Ja, Du hast ein Schicksal, das nicht immer leicht ist! Na und ! Es ist Deines und genau für Dich zugeschnitten; es ist nicht zu leicht und nicht zu schwer - passend eben.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[11]    = 'Wassermann: der Narr';
cardv[11]    = '11';
cardn[11]    = '11';
ctext[11]    = new Array(1);
ctext[11][0] = '[Text not found!]';
ctext[11][1] = 'Freue Dich nicht zu früh! So lustig ist es gar nicht, den Narren als Tageskarte zu ziehen! Oder weißt Du schon, wie Du Dir Flügel wachsen lassen kannst? Hast Du eine Ahnung, was Loslassen heute für Dich bedeuten könnte? Zugegeben, wenn Du es dann erledigt hast, wird es Dir gut gehen. Aber so ein Tag kann einem vorkommen, wie ein ganzes Leben. Wenn Du mutig bist kann der heutige Tag Dein weiteres Leben wirklich verändern. Wenn Du mutig bist, dann wird es ein wunderbarer Tag!<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[12]    = 'Fische: der Engel';
cardv[12]    = '12';
cardn[12]    = '12';
ctext[12]    = new Array(1);
ctext[12][0] = '[Text not found!]';
ctext[12][1] = 'Wir sind immer geführt, auch wenn wir es nicht merken. Heute könntest Du es spüren, könntest Deinen Engel, Deinen Schutzengel fühlen. Wenn Du etwas leiser bist, behutsam durch den Tag gehst, hast Du die Chance, dass Deine Seele berührt wird. Nimm Dir also nicht so viel vor, suche die Ruhe, die Einsamkeit und lausche! Und, falls Du heute nichts zu „hören“ vermagst, gräme Dich nicht, solche Tage kommen immer wieder.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[13]    = 'Krebs - Widder: der Trotz';
cardv[13]    = '5';
cardn[13]    = '13';
ctext[13]    = new Array(1);
ctext[13][0] = '[Text not found!]';
ctext[13][1] = 'Es gibt nichts, was mehr Widerstand „kreiert“ als ein unbewusstes „Nein“. Ein uraltes, Dir bekanntes Gefühl steckt hinter bestimmten Ereignissen Deines heutigen Tages: Trotz! Alter Kindertrotz! Wie lange willst Du den noch mit Dir herumtragen? Du wirst sowieso nicht bekommen, was Du willst – so nicht! Damals nicht und heute nicht! Sprich mit Deinem inneren Kind, rede ihm (Dir) gut zu und gib (endlich!) auf. Du wirst erstaunt sein, welche Wirkung das hat. Lass Dich überraschen!<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[14]    = 'Krebs - Stier: die zwei Gesichter der Eva';
cardv[14]    = '6';
cardn[14]    = '14';
ctext[14]    = new Array(1);
ctext[14][0] = '[Text not found!]';
ctext[14][1] = 'Ehefrau oder Geliebte? Ob Du Mann oder Frau bist, jeder Mensch hat mit diesem Thema, mit diesen zwei inneren Personen seine Mühe. Heute wird Dir bewusst werden, dass in Deiner Seele ein Ungleichgewicht herrscht. Du identifizierst Dich mehr mit einer der beiden Frauengestalten und Du tust gut daran das in Ordnung zu bringen. Gib der „Vernachlässigten“ mehr Raum in Deinem Leben! Dem Mond, der „Ehefrau“ indem Du mehr Fürsorge und seelische Nähe entwickelst, der Venus, der „Geliebten“ indem Du Dir selbst Gutes tust oder Dir von jemandem Etwas schenken lässt.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[15]    = 'Krebs - Zwillinge: die Aussprache';
cardv[15]    = '7';
cardn[15]    = '15';
ctext[15]    = new Array(1);
ctext[15][0] = '[Text not found!]';
ctext[15][1] = 'Um eine Aussprache kommst Du heute nicht herum. Es ist an der Zeit, dass Du Dich mitteilst, unausgesprochene Gedanken und Gefühle liegen Dir wie Blei im Magen. Es geht dabei um Ehrlichkeit Dir selbst und anderen gegenüber.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[16]    = 'Krebs - Löwe: die Unvereinbarkeit';
cardv[16]    = '9';
cardn[16]    = '16';
ctext[16]    = new Array(1);
ctext[16][0] = '[Text not found!]';
ctext[16][1] = 'Es gibt Tage, da bleibt dem Menschen nichts anderes übrig als an Ur-Themen zu arbeiten. Heute streiten Dein männlicher und Dein weiblicher Seelenanteil - Kopf und Bauch - miteinander. Gerade so, wie sie das seit der Vertreibung aus dem Paradies tun. Dafür gibt es keine Lösung. Die Entwicklung besteht darin, die Projektion auf das gegengeschlechtliche Gegenüber zurückzunehmen. Alles klar? Adam und Eva streiten in Dir, nicht da Draussen, bei den Männern und Frauen.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[17]    = 'Krebs - Jungfrau: die Fürsorge';
cardv[17]    = '10';
cardn[17]    = '17';
ctext[17]    = new Array(1);
ctext[17][0] = '[Text not found!]';
ctext[17][1] = 'Kümmere Dich, sorge Dich! -  Machst Du schon? -  Nicht um andere, um Dich selbst. Es wird Zeit, heute ist der richtige Tag damit zu beginnen. Bitte jemanden um einen Gefallen, auch wenn es noch so schwer fällt. Geh los und hole Dir etwas von der Welt und sei nicht beleidigt, wenn nicht sofort etwas kommt. Du musst das Nehmen erst üben. Es wird nur für denjenigen gesorgt, der mit offenen Händen auf das Leben zugeht.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[18]    = 'Krebs - Waage: die Familie';
cardv[18]    = '11';
cardn[18]    = '18';
ctext[18]    = new Array(1);
ctext[18][0] = '[Text not found!]';
ctext[18][1] = 'Mit dieser Tageskarte will sich heute Deine Familie in Dein Bewusstsein bringen. Ganz konkret (ein Besuch, ein Anruf) oder in Deinem Inneren. Bedenke: Dich gibt es nicht alleine. Du bist ein Teil eines Systems und mit den Mitgliedern Deiner Familie in Liebe und Loyalität verbunden (ob Dir das bewusst ist oder nicht). So manches Problem und Verhaltesmuster findet dort seinen Ursprung und kann auch nur dort gelöst werden. Mach Dich auf die Suche!<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[19]    = 'Krebs - Skorpion: die Abtreibung';
cardv[19]    = '12';
cardn[19]    = '19';
ctext[19]    = new Array(1);
ctext[19][0] = '[Text not found!]';
ctext[19][1] = 'Der Titel dieser Karte ist natürlich nicht wörtlich zu nehmen. Dennoch hat Dich ein grosses Seelenthema heute im Griff. Du hast zuviel von Dir und Deinen Gefühlen geopfert und musst dringend den Rückweg antreten und Heilung für Dein Herz suchen. Es ist immer ein langer Weg heraus zu kommen aus Abhängigkeiten und unguten Bindungen. Heute kann der erste Schritt sein!<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[20]    = 'Krebs - Schütze: Mnemosyne';
cardv[20]    = '13';
cardn[20]    = '20';
ctext[20]    = new Array(1);
ctext[20][0] = '[Text not found!]';
ctext[20][1] = 'Mnemosyne ist die Göttin der Erinnerung. Widme ihr Deinen heutigen Tag. Er steht ganz im Zeichen der Musen, ihrer Töchter. Beschäftige Dich nicht mehr als nötig mit den Alltags-Dingen des Lebens. Gib den Künsten, der Musik, der Poesie oder auch z.B. der Astrologie (der Himmelskunde) mehr Raum. Durch diese hindurch wird die „Göttin“ zu Deiner Seele sprechen und Du „er-Innerst“ Dich.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[21]    = 'Krebs - Steinbock: die Eiskönigin';
cardv[21]    = '14';
cardn[21]    = '21';
ctext[21]    = new Array(1);
ctext[21][0] = '[Text not found!]';
ctext[21][1] = 'Kein Mensch schafft es jeden Tag seines Lebens mit offenen Armen zu empfangen. Und manchmal ist das auch nicht notwendig. Oftmals ist es besser abzuwarten, zuerst Klarheit zu finden und sich eventuell vor Verletzungen zu schützten. Bleibe heute ganz bei Dir und kläre zuerst Deine Gefühlsituation. Erst wenn Du Deine Probleme niemandem mehr anlastest ist der Zeitpunkt gekommen, Dich zu öffnen und den „Panzer“ aufzugeben.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[22]    = 'Krebs - Wassermann: die Ent-Bindung';
cardv[22]    = '15';
cardn[22]    = '22';
ctext[22]    = new Array(1);
ctext[22][0] = '[Text not found!]';
ctext[22][1] = 'Wieder und wieder geht es im Leben ums Loslassen, in den kleinen und den grossen Dingen des Lebens. Und immer wieder hat der Mensch Angst vor dem Neuen, vor allem, was er nicht kennt. Heute darfst Du einen Schritt ins Unbekannte tun! Sei es in Deinem Inneren auf seelischer oder auf der sichtbaren Ebene des Seins; es ist Zeit aus dem „Sicherheits-Ei“ des Gewohnten zu schlüpfen und neu zu werden – und sei es nur für einen Tag.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[23]    = 'Krebs - Fische: der Dornröschen-Schlaf';
cardv[23]    = '16';
cardn[23]    = '23';
ctext[23]    = new Array(1);
ctext[23][0] = '[Text not found!]';
ctext[23][1] = 'Auf was/ wen wartest Du? Auch wenn Dornröschen hier auf dem Bild so friedlich schläft, geht es heute dennoch nicht ums Ausruhen, nicht ums Träumen. Das hast Du in irgendeinem Bereich Deines Lebens lange genug getan. Die „100 Jahre“ Schlaf sind heute vorbei! Es kommt niemand vorbei, der Dir die Sicherheit, die Geborgenheit gibt, die Du glaubst zu benötigen um „aufzustehen“, zu Dir zu stehen. Was Du brauchst besitzt Du längst: einen guten Zugang zu Deinem Innersten, Deiner Intuition. Nutze diese Gabe für diesen Tag, dieses Leben -  Dein Leben!<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[24]    = 'Löwe - Widder: der Kampf';
cardv[24]    = '6';
cardn[24]    = '24';
ctext[24]    = new Array(1);
ctext[24][0] = '[Text not found!]';
ctext[24][1] = 'Im Moment bist Du Dein ärgster Feind. Wohin soll das führen? Du kämpfst an der falschen Stelle!  Der Feind bist nicht Du selbst, sondern irgendjemand oder etwas im Aussen, irgend etwas ganz Reales, Greifbares. Nimm allen Mut zusammen und stelle Dich der Situation. Es bringt nichts Dich innerlich zu zerfleischen und dabei unendlich viel Energie zu verlieren. Ob Du dann (heute) siegen oder verlieren wirst, ist  nicht wirklich wichtig. Wichtig ist, dass Du –sofort !- aufhörst ein Opfer zu sein.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[25]    = 'Löwe - Stier: die Herrscherin';
cardv[25]    = '7';
cardn[25]    = '25';
ctext[25]    = new Array(1);
ctext[25][0] = '[Text not found!]';
ctext[25][1] = 'Ob Du Mann oder Frau, alt oder jung bist, heute geht es um den Einsatz sinnlicher Mittel, den Einsatz Deiner erotischen Ausstrahlung. Sieh es als ein Spiel an, Deine Attraktivität und Deinen Charme hervorzukehren und diese für Deine Wünsche und Ziele einzusetzen. Falsche Bescheidenheit und „heilige“ Skrupel bringen Dir nichts ein. Und: gib es zu, verlieren möchtest Du auf keinen Fall!<br />Da ist es schon ehrlicher den ganzen Einsatz zu bringen.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[26]    = 'Löwe - Zwillinge: der Schauspieler';
cardv[26]    = '8';
cardn[26]    = '26';
ctext[26]    = new Array(1);
ctext[26][0] = '[Text not found!]';
ctext[26][1] = 'Du hast gelernt, man soll immer echt und authentisch sein, mit seelischer Tiefe und viel Gefühl durchs Leben gehen. Das hat man Dir so beigebracht. Wer? Die Esoteriker? Deine Eltern? Deine Moral?<br />Nimm das Spiel des Lebens doch mal leicht! Spiel mit beim grossen Ego-Wettbewerb, das macht mehr Spass, als Du glaubst. Nichts ist in Anbetracht unseres doch sehr kurzen Lebens so wichtig, dass man sich damit belasten und beschweren sollte. Auf das Ganze geschaut spielen wir keine so grosse Rolle, es lohnt also nicht so ein Drama daraus zu machen.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[27]    = 'Löwe - Jungfrau: der kranke König';
cardv[27]    = '11';
cardn[27]    = '27';
ctext[27]    = new Array(1);
ctext[27][0] = '[Text not found!]';
ctext[27][1] = 'Aufstehen! Komm in die Gänge! Auch wenn heute nicht Dein Tag (Dein Leben?) ist, Du MUSST!!!! Schon klar, alles ist grau in grau und langweilig und Du bist eigentlich zu Höherem geboren. Mag schon sein, doch heute interessiert das niemanden. Du musst Dich schon bequemen Deine „königlichen Füsse“ auf den Boden der Realität zu stellen. Wer weiss, wann und ob überhaupt jemals ein roter Teppich für Dich ausgerollt wird?  Ein gute Rat: Warte nicht, besorge (erarbeite!) Dir selbst einen!<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[28]    = 'Löwe - Waage: die Hoch-Zeit';
cardv[28]    = '12';
cardn[28]    = '28';
ctext[28]    = new Array(1);
ctext[28][0] = '[Text not found!]';
ctext[28][1] = 'Eine so schöne Karte, ein so schönes Bild! Heute findet  Dich die Liebe, das Glück ist auf dem Weg zu Dir! Du darfst Dich allerdings nicht verstecken. Falls dem doch so ist und Du etwas daran ändern möchtest, hier einige sehr beliebte „Verstecke“: Du machst einen anderen Menschen für Dein Glück verantwortlich. Du glaubst ohne Partner besser dran zu sein. Du hängst an einem vergangenen Glück und wartest, dass es wiederkommt. Zwischen Dir und Deinen Mitmenschen ist Geben und Nehmen nicht im Einklang. Usw., usw, beim „Verstecken“hat jeder so seine Vorlieben.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[29]    = 'Löwe - Skorpion: der Magier';
cardv[29]    = '13';
cardn[29]    = '29';
ctext[29]    = new Array(1);
ctext[29][0] = '[Text not found!]';
ctext[29][1] = 'Dein Perfektionismus legt Dir (und Deinem Umfeld) geistige Fesseln an und Du merkst es nicht einmal. Wenn Du nur halb so perfekt, so gut wärest, wäre es immer noch ausreichend. Du würdest viel Energie, viel kostbare Lebensenergie sparen. Du könntest damit wundervolle, sinnvolle Dinge vollbringen, Dinge, die Dir Freude bereiten und Dich erfüllen könnten.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[30]    = 'Löwe - Schütze: Fortuna';
cardv[30]    = '14';
cardn[30]    = '30';
ctext[30]    = new Array(1);
ctext[30][0] = '[Text not found!]';
ctext[30][1] = 'Heute ist Dein Tag! Was immer Du beginnst, es wird Dich zum Erfolg führen, Dich glücklich machen. Auch wenn dies noch nicht sofort zu erkennen sein sollte, hab Vertrauen, es wird sich irgendwann zeigen. Manchmal kann der Mensch nicht gleich sehen, dass die „Götter“ es gut mit ihm meinen. In dem „Füllhorn“, das sie über ihm ausschütten befinden sich mitunter „Gaben“, die ihren Sinn erst später zeigen. Deshalb: schreibe Dir heute die Geschehnisse des Tages auf und lies später einmal nach, Du wirst Dich wundern.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[31]    = 'Löwe - Steinbock: die Bürde';
cardv[31]    = '15';
cardn[31]    = '31';
ctext[31]    = new Array(1);
ctext[31][0] = '[Text not found!]';
ctext[31][1] = 'Wie gut, dass Du diese Karte für nur einen Tag gezogen hast, so musst Du die schwere Bürde nicht für all zu lange Zeit tragen. Ein Tag, der heutige reicht aus um einen Weg zu beginnen, der zwar sehr mühsam, aber unumgänglich ist. Der heutige Tag ist der Tag, den Du schon lange versuchst zu vermeiden. Geh ihn an! Geh sie an, Deine Probleme! Jetzt sofort! Mach einen Plan und starte mit dem ersten Schritt, es ist der erste und der wichtigste Schritt auf dem Weg zu einer Lösung. Schon Morgen kann dann alles leichter sein.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[32]    = 'Löwe - Wassermann: der Sturz';
cardv[32]    = '16';
cardn[32]    = '32';
ctext[32]    = new Array(1);
ctext[32][0] = '[Text not found!]';
ctext[32][1] = 'Heute hast Du die Wahl: Schau Dir die beiden Gestalten auf der Karte an und wähle, wer Du heute sein möchtest: „König Ego“, der mit schiefer Krone auf seinem „Allerwertesten“ sitzt und die Welt nicht mehr versteht oder der Narr, der fröhlich auf der Lehne des Thrones sitzend dem König den Spiegel vorhält. Kurzum: entweder Du ärgerst Dich und bleibst beleidigt „hocken“ oder Du lachst über Dich selbst, über die „Ego-Spielchen“, die Du (wir alle) so treiben und leider viel zu ernst nehmen.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[33]    = 'Löwe - Fische: der Rückzug';
cardv[33]    = '17';
cardn[33]    = '33';
ctext[33]    = new Array(1);
ctext[33][0] = '[Text not found!]';
ctext[33][1] = 'Wahrscheinlich hast Du Dir oft vorgenommen mal wieder (oder überhaupt) zu meditieren oder Dich mehr um Dein Inneres zu kümmern. Bis heute vergeblich: keine Zeit, keine Lust usw. Doch heute ist der Tag, der erste Tag, an dem es Dir gelingen kann Dich Deiner Seele anzuvertrauen und Dich einer inneren Führung zu überlassen. Je mehr Kontrolle Du abgibst, desto besser wirst Du Dich dabei fühlen.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[34]    = 'Widder - Stier: das Eros';
cardv[34]    = '3';
cardn[34]    = '34';
ctext[34]    = new Array(1);
ctext[34][0] = '[Text not found!]';
ctext[34][1] = 'Es gibt kaum eine schönere Zeit, als die Zeit der Verliebtheit. Von Eros Pfeil getroffen, tanzt der Mensch beschwingt, fröhlich und mit einem Lächeln durch sein Leben. Ach, könnte es nur immer so sein! Kann es, wenn Du nur willst. Wenn Du Deine Gefühle nicht mehr abhängig machst von dem, was Dir von Aussen entgegen kommt, von der Verliebtheit in einen Menschen (kommt zu selten vor). Verliebe Dich in das Leben! Warte nicht darauf, dass der Pfeil  Dich trifft. Sende Du Deinen Eros hinaus in die Welt, lege eine „Liebeslinie“ von Dir zu all dem, was Dir begegnet, wähle den Weg, den Du gehst mit ganzem Herzen – heute!<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[35]    = 'Widder - Zwillinge: der Pranger';
cardv[35]    = '4';
cardn[35]    = '35';
ctext[35]    = new Array(1);
ctext[35][0] = '[Text not found!]';
ctext[35][1] = 'Zugegeben, die Welt ist unvollkommen, die Menschen sind es und Du bist es. Ganz besonders heute spürst Du dies mal wieder sehr deutlich. Tratsch, Klatsch und üble Nachrede vergiften Deinen Tag. Ob Du dabei „Täter“ oder „Opfer“ bist, ist nicht so wichtig, wie Du vielleicht denkst. Verwickelt und betroffen bist Du so oder so. Deinem Seelenfrieden zuliebe, beende dieses „Spiel“ so schnell Du kannst. Spricht man über Dich, dann oute Dich und veröffentliche das, um was geht. Bist Du der „Kritiker“, höre einfach auf damit , es zieht Dich runter, kostet Dich unnötig Energie und kommt noch dazu postwendend wie ein Bumerang zu Dir zurück.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[36]    = 'Widder - Jungfrau: die Schuld';
cardv[36]    = '7';
cardn[36]    = '36';
ctext[36]    = new Array(1);
ctext[36][0] = '[Text not found!]';
ctext[36][1] = 'Es ist aussichtslos  heraus zu finden, wer nun Schuld an der Situation hat, in der Du steckst. Diese Frage lässt sich beim besten Willen nicht beantworten. Wer war zuerst, die Henne oder das Ei? <br />Diese Überlegungen führen nicht weit. Betrachte das Ganze vom Lösungsstandpunkt aus: Was kannst Du jetzt – heute – tun um weiter zu gehen. Die Aufgabe besteht darin Deine Kraft wieder zu finden- ganz ausserhalb von gut und böse, von recht und unrecht. Triff eine Entscheidung für DICH, nicht gegen jemanden!<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[37]    = 'Widder - Waage: der Streit';
cardv[37]    = '8';
cardn[37]    = '37';
ctext[37]    = new Array(1);
ctext[37][0] = '[Text not found!]';
ctext[37][1] = 'Auch wenn Du normalerweise ein ganz lieber, friedlicher Mensch bist,  heute geht es nicht darum das unter Beweis zu stellen, heute wird es Dir nicht gelingen einer Auseinandersetzung aus dem Weg zu gehen. Nimm allen Mut zusammen und stelle dich dem „Feind“! Wenn Du den Konflikt weiterhin mit „Scheinharmonie“ zudeckst, bleibt Deinem Gegenüber nichts anderes übrig als dass er sich gezwungen fühlt,  Deine unbewussten Aggressionen auszuagieren und sie Dir vor die „Füsse“ zu werfen. Und somit landet das „Problem“ sowieso wieder bei Dir. Du siehst, es lohnt sich nicht es fort zu schicken, es kommt  wie ein Bumerang zurück –wieder und wieder- bis Du gelernt hast ab und zu auf ein „Wir“ zu verzichten und Deinem „Ich“ den Vorzug zu geben. Dann könnt Ihr auch wieder Freunde sein, Du und  Dein „Feind“, Du und Dein Problem.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[38]    = 'Widder - Skorpion: der Vampir';
cardv[38]    = '9';
cardn[38]    = '38';
ctext[38]    = new Array(1);
ctext[38][0] = '[Text not found!]';
ctext[38][1] = 'Es ist schon recht, wenn Du Dich ein bisschen vor dieser Karte, vor diesem Tag fürchtest. Es erfordert viel Klarheit und Kraft sich zu lösen, wenn man so verstrickt ist wie Du. Du bist an irgend etwas oder irgend jemanden so sehr (bewusst oder unbewusst) gebunden, dass diese Bindung Dir – vielleicht ohne, dass Du es merkst – Energie raubt. Überprüfe heute sehr sorgfältig, wie es um Deinen Energie-Haushalt bestellt ist und ob Du da, wo Du (Lebens-) Kraft hineinsteckst auch wirklich etwas herausbekommst. Wenn nicht, so hilft nur eines: Du musst dich sofort lösen, musst das – um was auch immer es sich handelt – abtrennen von Deinem „System“. Du hast gehofft, dass Dir etwas Lebendigkeit verleiht. Dieses Etwas ist nun zu eine Art Schmarotzer geworden, ein "Parasit, der Dir den Blick auf die Zukunft nimmt".<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[39]    = 'Widder - Schütze: der Kreuzritter';
cardv[39]    = '10';
cardn[39]    = '39';
ctext[39]    = new Array(1);
ctext[39][0] = '[Text not found!]';
ctext[39][1] = 'Es gibt zwei Möglichkeiten Deine Tageskarte zu deuten: Entweder Du handelst in irgend einer Sache uneinsichtig und gegen besseres Wissen oder Du müsstest den Mut entwickeln endlich zu Deiner Meinung zu stehen und dafür zu kämpfen. Obwohl es aussieht als wären dies zwei ganz unterschiedliche Aufgaben, so steckt doch eine Aussage dahinter: erst die Einsicht, dann das Handeln! Also fehlt Dir entweder die Einsicht oder es fehlt Dir der Mut zu handeln oder Du hältst die Reihenfolge nicht ein.<br />Heute ist ein guter Tag die beiden Energien sinnvoll zusammen zu bringen und diesen Tag kraftvoll zu bestreiten.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[40]    = 'Widder - Steinbock: die Verhinderung';
cardv[40]    = '11';
cardn[40]    = '40';
ctext[40]    = new Array(1);
ctext[40][0] = '[Text not found!]';
ctext[40][1] = 'Heute geht es nicht –wirklich nicht! - darum mit dem Kopf durch die Wand zu wollen. Du kämpfst an der falschen Stelle, zur falschen Zeit. Gib auf! Es ist jetzt nicht an Dir zu entscheiden wohin sich die Dinge entwickeln. Überlasse es –ausnahmsweise mal- dem Schicksal, was aus der „Sache“ für die Du Dich zuständig fühlst wird. Es liegt nicht alles in Deinen Händen, das Schicksal hat auch eine Wörtchen mit zu reden. Besonders, wenn es sich um das Schicksal Deiner Mitmenschen handelt, vergeudest Du Deine Energie. Es werden wieder andere Tage kommen, Tage, an denen Deine Kraft und Dein Wille „gefragt“ sind und das „Schwert“ sich leicht aus dem „Stein“ ziehen lässt.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[41]    = 'Widder - Wassermann: der Giftzwerg';
cardv[41]    = '12';
cardn[41]    = '41';
ctext[41]    = new Array(1);
ctext[41][0] = '[Text not found!]';
ctext[41][1] = 'Wie am Bild der Karte zu  erkennen ist, wirst Du heute im Inneren oder im Aussen eine wichtige Bekanntschaft machen. Du wirst Rumpelstilzchen, dem Giftzwerg, der Dir eine lange Nase macht, begegnen. Auf den ersten Blick eine unangenehme Begegnung: Du wirst verraten, hintergangen, gemobbt, oder Du stellst Dir selbst ein Bein. Zurecht! Auch wenn Du es nicht sofort zu erkennen vermagst, das Ganze macht Sinn, Du wirst es eines Tages verstehen. Du bist den „Helfern“ der Veränderung und Befreiung begegnet, den Freunden, die zuerst aussehen wie Feinde und denen Du zum Schluss doch dankbar sein wirst, dass sie Dir den Weg für Neues geebnet haben, auch wenn die Methode schmerzhaft war.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[42]    = 'Widder - Fische: der reine Tor';
cardv[42]    = '13';
cardn[42]    = '42';
ctext[42]    = new Array(1);
ctext[42][0] = '[Text not found!]';
ctext[42][1] = 'Heute könntest Du genau so gut im Bett bleiben. Es steht Dir für die Tageswelt wenig Energie zu Verfügung. Gut möglich, dass Du einfach müde bist vom ewigen Existenzkampf, mag sein, dass Du  von etwas berührt wurdest und Dir noch keine Zeit genommen hast es aufzuarbeiten. Auf jeden Fall geht es heute darum, mehr nach innen zu schauen, als nach aussen. Vergiss nicht, es gibt zwei Welten, eine sichtbare und eine unsichtbare. Kümmere Dich heute um die unsichtbare, die Welt der Träume, der Phantasien oder wie die Schamanen sagen um die „Nicht-alltägliche- Wirklichkeit, auch Nagual genannt.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[43]    = 'Stier - Zwillinge: die Goldmarie';
cardv[43]    = '5';
cardn[43]    = '43';
ctext[43]    = new Array(1);
ctext[43][0] = '[Text not found!]';
ctext[43][1] = 'Wovon hängt es ab, ob der Mensch sich glücklich oder unglücklich fühlt? Wovon hängt Deine Definition von Pech oder Glück ab? Ist es nicht nur eine Frage der Sichtweise? Wer in Dir bestimmt, wie Du Dich fühlst? Ist es nicht dein Ego, dass Dir, wenn Du Dich unterlegen fühlst (ob einem Menschen oder dem Leben gegenüber bleibt sich gleich) einflüstert Du wärest ein „Pechvogel“ und alle anderen hätten es besser? Glaubst Du wirklich auf dieser Ebene des Erlebens eine Lösung zu finden und es würde sich lohnen, es besser machen, sich noch mehr anstrengen? Dein bisheriges Leben hat Dir sicherlich schon gezeigt, dass das aussichtlos ist. Wenn nicht, der heutige Tag ist denkbar gut geeignet dieses sinnlose Spiel zu beenden. Es gibt auch ein Leben ohne Konkurrenz, ohne ständige Vergleiche. In diesem Leben gibt es keine Verlierer (allerdings auch keine Gewinner!)<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[44]    = 'Stier - Jungfrau: das Festhalten';
cardv[44]    = '8';
cardn[44]    = '44';
ctext[44]    = new Array(1);
ctext[44][0] = '[Text not found!]';
ctext[44][1] = 'Hast Du ein Geldproblem? Oder macht sich das Thema „Sicherheit“ bei Dir anders bemerkbar? Auf jeden Fall ist ein Übermass von etwas daran Schuld, dass Du so unbeweglich bist. Schmeiss irgendetwas von „Bord“, dann wirst du automatisch leichter. Was könnte das heute sein? Müsstest Du etwas ausmisten? Dich von etwas trennen, was längst überfällig ist?<br />Um was auch immer es sich handelt, vergiss nicht, dass Materie zwar ihren Stellenwert hat, doch nicht zum Sinn des Lebens erhoben werden darf. Schau auf das, was Du für Deine Sicherheit opferst und frage Dich ob es sich lohnt.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[45]    = 'Stier - Waage: der goldene Käfig';
cardv[45]    = '9';
cardn[45]    = '45';
ctext[45]    = new Array(1);
ctext[45][0] = '[Text not found!]';
ctext[45][1] = 'Niemand auf dieser Welt ist frei von Lob und Anerkennung. Wir alle brauchen Bestätigung, besonders die des Partners. Die Frage ist nur, was wir dafür in Kauf nehmen. Sobald wir den Anderen (oder bestimmte Umstände) zu sehr zur Absicherung unseres Ichs brauchen und gebrauchen, verlieren wir an Eigenständigkeit und Kraft. Mit dem Ziehen dieser Karte will Deine Seele Dich darauf aufmerksam machen, dass etwas nicht im Lot, nicht im Gleichgewicht ist. Durch irgendetwas lässt Du Dich „kaufen“. Überprüfe das mal und überlege, wie Du die „Käfigtüre“ öffnen könntest.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[46]    = 'Stier - Skorpion: die Marionette';
cardv[46]    = '10';
cardn[46]    = '46';
ctext[46]    = new Array(1);
ctext[46][0] = '[Text not found!]';
ctext[46][1] = 'Du hängst an unsichtbaren Fäden. Alte, übernommene Werte beeinflussen Dich und lassen Dich unfrei denken und handeln. Stelle Dir heute die Frage: An welcher Stelle meines Lebens folge ich, fremden Bildern, Vorstellungen oder Werten? Schau dabei besonders auf Deine Sippe und mache Dir bewusst, dass Du eventuell jemandem folgst, seine Lebensgeschichte nachahmst, oder Dein Schicksal dem eines anderen gleicht. Wenn Du es heraus gefunden hast, so ist dies der erste Schritt zur Lösung.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[47]    = 'Stier - Schütze: Materie und Geist';
cardv[47]    = '11';
cardn[47]    = '47';
ctext[47]    = new Array(1);
ctext[47][0] = '[Text not found!]';
ctext[47][1] = 'Einsichten alleine bedeuten noch gar nichts. Man kann sie zwar kaufen (in Beratungen z.B.) aber es reicht nie, dass der „Kopf“ klug geworden ist. Du hast längst gemerkt, dass Dir zur wirklichen Veränderung noch etwas fehlt: Die seelische Erfahrung, der durchlebte Prozess. Der heutige Tag bietet Dir genug „Stoff“ um einen wichtigen Schritt in Deiner Entwicklung zu machen, vielleicht den wichtigsten überhaupt: Du darfst noch einmal zurück an den Anfang des Problems, der Situation kehren um Dir bewusst zu werden wo Du wirklich stehst.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[48]    = 'Stier - Steinbock: die Verantwortung für die Schöpfung';
cardv[48]    = '12';
cardn[48]    = '48';
ctext[48]    = new Array(1);
ctext[48][0] = '[Text not found!]';
ctext[48][1] = 'Schau Dich einmal in Deiner näheren Umgebung um. Befindet sich hier ein hilfsbedürftiges Wesen? Eine Pflanze, die Wasser braucht? Ein Tier, dass Du vernachlässigt hast? Oder eventuell ein Mensch, dem Du helfen könntest? Die wahren Aufgaben befinden sich immer in unmittelbarer Nähe, niemand muss dafür weit reisen. Aber beachte eines: wem auch immer Du helfen möchtest, er MUSS wirklich schwach sein und Hilfe benötigen. Solltest Du niemanden finden, so hat die Karte für Dich die gegenteilige Bedeutung: Hör auf zu helfen, Du masst Dir da etwas an! Die Person um die es geht ist erwachsen und selbst verantwortlich!<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[49]    = 'Stier - Wassermann: der Abschied';
cardv[49]    = '13';
cardn[49]    = '49';
ctext[49]    = new Array(1);
ctext[49][0] = '[Text not found!]';
ctext[49][1] = 'Viele, viele Abschiede gehören zum Lebensweg des Menschen. Ob grosse oder kleine, es tut immer ein bisschen weh, wenn man gerne bleiben oder etwas behalten möchte. Auch heute hält das Leben mal wieder diese Erfahrung für Dich bereit und verlangt von Dir etwas loszulassen, und sei es noch so etwas „Kleines“. Das Schicksal verordnet Dir einen Aufbruch, einen neuen Weg zu beschreiten. Auf dem alten bist Du zu unbeweglich, zu schwer geworden. Vergiss nicht: Selbst das kleinste abgeworfenen Gewicht zählt, wenn man vorhat sich zu bewegen.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[50]    = 'Stier - Fische: der Garten der Geister';
cardv[50]    = '14';
cardn[50]    = '50';
ctext[50]    = new Array(1);
ctext[50][0] = '[Text not found!]';
ctext[50][1] = 'Diese Karte wird selten als Tageskarte gezogen, da sie ein zu grosses Thema umfasst, als dass es in 24 Stunden erfahren werden könnte. Für Dich allerdings beginnt heute ein wichtiger Entwicklungsprozesses, dessen Ziel es ist, die Welt mit anderen Augen zu sehen. Es ist für Dich an der Zeit HINTER die Dinge zu schauen, der sichtbaren Welt nicht mehr soviel Gewicht zu geben. „Jede Erscheinung auf Erden ist nur ein Gleichnis, ein Tor“, sagt Hesse. Wir müssen nur durch dieses Tor hindurch treten, um ein ganzheitliches Verständnis zu bekommen. Jeder Tag ist der richtige damit zu beginnen.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[51]    = 'Zwillinge - Jungfrau: der Stratege';
cardv[51]    = '9';
cardn[51]    = '51';
ctext[51]    = new Array(1);
ctext[51][0] = '[Text not found!]';
ctext[51][1] = 'Handle heute klug und wohlüberlegt! Nimm Dir Zeit zum Nachdenken und plane Deine Vorhaben sehr sorgfältig. Es geht im Moment nicht darum spontan zu sein und etwas zu entscheiden. Verschaffe Dir zuerst einen Überblick und bedenke alle Konsequenzen, bevor Du den nächsten Schritt machst.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[52]    = 'Zwillinge - Waage: Marktplatz der Eitelkeiten';
cardv[52]    = '10';
cardn[52]    = '52';
ctext[52]    = new Array(1);
ctext[52][0] = '[Text not found!]';
ctext[52][1] = 'Die ganze Welt ist ein Marktplatz. Das Spiel: sehen und gesehen werden ist eines der liebsten Spiele des Menschen. Niemand kann sich da ganz raushalten, auch Du nicht. Doch miss dem Ganzen nicht zu viel Bedeutung zu! Besonders Deine Partnerschaft oder eventuell Deine Freundschaften brauchen mehr von Dir als dieses Spiel. Diese Bereiche verlangen im Moment mehr Einsatz und mehr Tiefe von Dir. Irgend jemand in Deinem Umfeld möchte sich nicht mit Deiner „Oberflächlichkeit“ zufrieden geben. Nimm das als Anregung und freue Dich darüber, Du bist für jemanden wichtig.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[53]    = 'Zwillinge - Skorpion: der Rattenfänger';
cardv[53]    = '11';
cardn[53]    = '53';
ctext[53]    = new Array(1);
ctext[53][0] = '[Text not found!]';
ctext[53][1] = 'Folgende Frage solltest Du Dir heute stellen: Welchen Versprechungen, welchen Bildern  folge ich? Wem gehe ich auf den Leim? Welchen fremden „Flötentönen“ laufe ich nach, statt eine eigene „Melodie“ zu „komponieren“ und nach eigener Musik zu tanzen? Die Karotte, die Du gerade vor der Nase hast wird Dich nicht nähren, sie ist nicht wirklich gehaltvoll. Sobald Du erkennst, dass Du Dich hast verführen lassen, ist der „Spuk“ auch schon vorbei und Du bist frei, frei für eigene Gedanken, einen individuellen Weg.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[54]    = 'Zwillinge - Schütze: Meister und Schüler';
cardv[54]    = '12';
cardn[54]    = '54';
ctext[54]    = new Array(1);
ctext[54][0] = '[Text not found!]';
ctext[54][1] = 'Es gibt zwei Möglichkeiten Deine heutige Karte zu deuten. Es gehört zum Wesen dieser Karte, dass <b>Du</b> entscheidest welche der beiden auf Dich zutrifft. Entweder ist es für Dich an der Zeit Gelerntes endlich umzusetzen, Meister, Lehrer zu werden und Dein Wissen anderen zur Verfügung zu stellen. Oder: Du gibst Dich schon zu lange mit einem Wissenstand zufrieden und hast in der letzten zeit nichts mehr Neues dazu gelernt. Dann mache Dich auf zu neuen geistigen Ufern. Wenn Du offen bist, wirst Du heute einen Hinweis darauf bekommen, um was es sich dabei handeln könnte<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[55]    = 'Zwillinge - Steinbock: das Gebrechen';
cardv[55]    = '13';
cardn[55]    = '55';
ctext[55]    = new Array(1);
ctext[55][0] = '[Text not found!]';
ctext[55][1] = 'Nicht in jeder Lebensphase , nicht an jedem Tag laufen die Dinge des Lebens nach Wunsch. So ist das eben! Heute geht alles schleppend und langsam, Hindernisse liegen auf Deinem Weg, Du trittst auf der Stelle.<br />Der Sinn einer „Verlangsamung“ liegt auf der Hand: Du lernst diese Stelle Deines Seins besonders gut kennen. Du MUSST sie Dir notgedrungen genauer anschauen, musst Geduld entwickeln, mehr Verantwortung für den Status Quo übernehmen. Leichter wirst du dann von alleine wieder, da mach Dir mal keine Sorgen.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[56]    = 'Zwillinge - Wassermann: Hans guck in die Luft';
cardv[56]    = '14';
cardn[56]    = '56';
ctext[56]    = new Array(1);
ctext[56][0] = '[Text not found!]';
ctext[56][1] = 'Brich aus, aus dem Alltag, springe heute heraus aus den langweiligen Wiederholungen  Deines Seins. Mache heute irgend etwas, und mag es Dir noch so unwichtig erscheinen, einmal ganz anders als üblich. Fahre z.B. einen anderen Weg zum Geschäft, kleide Dich anders farbig, wechsle den Stil, iss etwas, was du noch nicht probiert hast. Was auch immer Dir einfällt ist gut, es muss nur von dem abweichen, was Du sonst tust. Es soll ein Symbol sein mit dem Du Deiner Seele versprichst, auch in grösseren Dingen neue Wege zu gehen.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[57]    = 'Zwillinge - Fische: das Schweigen';
cardv[57]    = '15';
cardn[57]    = '57';
ctext[57]    = new Array(1);
ctext[57][0] = '[Text not found!]';
ctext[57][1] = 'Versuche heute nicht Deine Welt zum funktionieren zu bringen, es wird Dir nicht gelingen. So sehr Du Dich auch abmühst, das Schicksal lässt sich heute nicht in die Karten schauen, die „Götter“ schweigen. Die Dinge reagieren nicht auf Dich, es herrscht Chaos und Dir bleibt nicht anderes übrig als still zu halten, zu vertrauen und mit zu schweigen. So kannst Du etwas vom Grossen- Ganzen und seiner Gesetzmässigkeit erahnen.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[58]    = 'Jungfrau - Waage: der Beziehungs-Alltag';
cardv[58]    = '13';
cardn[58]    = '58';
ctext[58]    = new Array(1);
ctext[58][0] = '[Text not found!]';
ctext[58][1] = 'Ist dein Leben langweilig und fad? Deine Beziehung und Deine Freundschaften ohne grosse Bewegung? Ist alles unendlich durchschnittlich und glanzlos? Dann: Willkommen in der Wirklichkeit, DEINER Wirklichkeit! DU bist langweilig geworden, Du hast aufgehört zu lernen, neue Erfahrungen zu machen. Dein heutiger Schritt könnte darin bestehen das zu ändern. Wie wäre es mit einer interessanten Übung: lenke alle Aufmerksamkeit auf den Augenblick, betrachte den (Beziehungs-) Alltag als gäbe es keine andere Möglichkeit Dich zu entwickeln und Erfahrungen zu sammeln. Du wirst sehen, Deine Energie und Deine Aufmerksamkeit werden Wunder bewirken.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[59]    = 'Jungfrau - Skorpion die Kasteiung';
cardv[59]    = '14';
cardn[59]    = '59';
ctext[59]    = new Array(1);
ctext[59][0] = '[Text not found!]';
ctext[59][1] = 'Es gibt Tage, da weiss man erst am Abend wie unsinnig ein bestimmtes Verhalten war oder wie ergebnislos man seine Energie eingesetzt hat. Heute könnte so ein Tag sein. Du grübelst zuviel, Du quälst Dich mit etwas herum und schadest Dir damit nur selbst. Schau Dir die Karte mit dem Bild der sich kasteienden Nonne gut an. Glaubst Du Gott oder sonst irgend jemand will, dass sie sich selbst verletzt? Bringt es ihr etwas? Nein, genau so wenig bringt es Dir etwas in Deinem Leben, wenn Du Dich weiter im Kreise drehst um Dein Bestes zu gebe. So wie es ist –so wie Du bist- ist es allemal gut genug.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[60]    = 'Jungfrau - Schütze: die Inquisition';
cardv[60]    = '15';
cardn[60]    = '60';
ctext[60]    = new Array(1);
ctext[60][0] = '[Text not found!]';
ctext[60][1] = 'Zwei Deiner inneren Personen, inneren Seelenanteile, streiten sich. Die eine fühlt sich gross und erhaben, hat einen riesigen Anspruch und kritisiert Dich, was immer Du tust. Und die andere fühlt sich dem entsprechend klein und als Versager. Wie es im Leben so ist, kann auch eine der beiden von jemandem im Aussen dargestellt werden. Die Aufgabe bleibt dennoch gleich: Hör auf Dich zwischen den Polen zu zerreissen. Das Schicksal wird Dir heute zur Seite stehen, damit Du lernst toleranter und liebevoller mit Dir um zu gehen. Es ist ganz einfach: weniger Anspruch und Grösse = weniger Versagens-Gefühl und Klein-sein.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[61]    = 'Jungfrau - Steinbock: die Angst';
cardv[61]    = '16';
cardn[61]    = '61';
ctext[61]    = new Array(1);
ctext[61][0] = '[Text not found!]';
ctext[61][1] = 'Angst haben wir alle. Irgendwo in unserem Inneren lauert sie und wartet auf eine Gelegenheit sich zu zeigen. Es nutzt  nicht, sie zu verdrängen, sie verschwindet nie für immer. Das einzige, was man tun kann –was Du heute tun kannst- ist ihr tapfer ins Auge zu sehen, sie zu konfrontieren.<br />Vielleicht, wenn du Glück hast, handelt es sich heute nur um einen kleinen „Ableger“ der grösseren Ängste. Die Aufgabe ist dennoch die gleiche: Hinschauen und weitergehen! Beschäftige Dich nicht zu lange mit ihr, das schwächt ebenso, wie sie zu ignorieren. Am besten Du gibst deiner Angst einen Namen und machst sie Dir damit (irgendwie) zu Freund.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[62]    = 'Jungfrau - Wassermann: die Erinnyen';
cardv[62]    = '17';
cardn[62]    = '62';
ctext[62]    = new Array(1);
ctext[62][0] = '[Text not found!]';
ctext[62][1] = 'Deine heutige Tageskarte zeigt, dass du an einem wichtigen Punkt deines Lebens angelangt bist. Schon lange trägst du etwas in Deinem Inneren herum, was nicht zu Dir gehört. Irgend etwas Fremdes, möglicherweise aus Deinem Herkunfts-System belastet Dich, macht Dich unruhig, vielleicht sogar ängstlich. Die Lösung liegt hier –so die Erinnyen- auf keinen Fall in der Gegenwart. Nur ein umfassender Such-Prozess kann Deine Seele erleichtern. Mit dem Ziehen dieser Tageskarte hat er heute begonnen.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[63]    = 'Jungfrau - Fische: die Täuschung';
cardv[63]    = '18';
cardn[63]    = '63';
ctext[63]    = new Array(1);
ctext[63][0] = '[Text not found!]';
ctext[63][1] = 'Heute musst Du sehr aufpassen. Entweder jemand will Dich bewusst hinters Licht führen oder Du täuscht Dich selbst, willst an irgend einem Punkt nicht so genau hinschauen. Vielleicht, weil es so bequemer ist? Eine Lüge entlarvt man am schnellsten, wenn man sich das Schlimmste  vorzustellen vermag. Das Schlimmste ist immer das, was man die ganze Zeit versucht zu vermeiden. Durchdenke das Ganze erst einmal als wäre es ein Spiel, der Ernst kommt gegebenenfalls von ganz allein.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[64]    = 'Waage - Skorpion: das Verhängnis';
cardv[64]    = '15';
cardn[64]    = '64';
ctext[64]    = new Array(1);
ctext[64][0] = '[Text not found!]';
ctext[64][1] = 'Der heutige Tag verlangt viel von Dir. Es ist an der Zeit einem „Dämon“, den Du selbst gerufen hast ins Auge zu blicken. Du hast zu viel Energie an jemanden gebunden und bist nun unfrei geworden. Vielleicht bist du auf ein Bild hereingefallen oder hast Dich einer Illusion von Liebe und Beziehung hingegeben, die nun der Realität nicht standhält. Nur mit einem Partner, der Dir vom Schicksal zugeführt wird, ist es möglich auf Dauer glücklich zu werden. Und selbst dann ist es wichtig ihn zu jeder Zeit auch wieder gehen lassen zu können.<br />Zugegeben: für uns alle eine schwere, doch erlernbare Aufgabe.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[65]    = 'Waage - Schütze: das Symbolon';
cardv[65]    = '16';
cardn[65]    = '65';
ctext[65]    = new Array(1);
ctext[65][0] = '[Text not found!]';
ctext[65][1] = 'Diese Karte bedeutet Glück in der Partnerschaft, Glück in Beziehungen. Gemeint ist das Glück, das entsteht, wenn man mit Menschen unterwegs ist mit denen man wachsen und sich entwickeln kann. Aus der Gemeinsamkeit heraus entsteht einfach mehr, als wenn der Mensch alleine durchs Leben geht. Achte und geniesse am heutigen Tag Deine Zugehörigkeit zu dem/der „einen“, zu den „vielen“ und letztlich zur Menschheit selbst.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[66]    = 'Waage - Steinbock: die Trauer';
cardv[66]    = '17';
cardn[66]    = '66';
ctext[66]    = new Array(1);
ctext[66][0] = '[Text not found!]';
ctext[66][1] = 'Natürlich bedeutet diese Karte nicht, dass heute jemand von Dir geht oder gar stirbt. Mit dieser Tageskarte können viele Themen verbunden sein. Zusammengefasst  geht es darum in jeder Phase Deines Lebens damit zu rechnen, dass alles seine Zeit hat, dass nichts für immer ist. Dies bedeutet nicht unentwegt auf das Ende zu schauen und sich eventuell damit zu quälen. Nur heute, heute ist so ein Tag an dem Du Dir der Vergänglichkeit, besonders der von Beziehungen bewusst werden sollst. Doch nicht um zu leiden, sondern im Gegenteil: Dein Herz wird dann um so wacher in der Gegenwart leben und Du wirst das, was Du hast um so mehr zu schätzen wissen.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[67]    = 'Waage - Wassermann: die Trennung';
cardv[67]    = '18';
cardn[67]    = '67';
ctext[67]    = new Array(1);
ctext[67][0] = '[Text not found!]';
ctext[67][1] = 'Wieder und wieder geht es im Leben darum sich zu verändern, zu überprüfen, wo man festgefahren ist und Konsequenzen daraus zu ziehen. So auch heute: Dein „Beziehungsprogramm“ braucht dringend eine Erneuerung. Es ist durchaus möglich auch INNERHALB einer Beziehung frei zu sein! Freiheit besteht allerdings nicht darin das „Ego“ machen zu lassen, was es will (das ist zu einfach), sondern die „Tür“ der Gemeinschaft immer offen stehen zu lassen, sodass jeder jederzeit herein und heraus gehen kann.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[68]    = 'Waage - Fische: die zwei Königskinder';
cardv[68]    = '19';
cardn[68]    = '68';
ctext[68]    = new Array(1);
ctext[68][0] = '[Text not found!]';
ctext[68][1] = 'Heute könnte der Tag sein, an dem Du aus Deinem „Beziehungstraum“ aufwachst und der Tatsache ins Auge siehst, dass Du Dir über das, was Liebe ist (eventuell die Liebe zu einer ganz bestimmten Person) Illusionen gemacht hast. Es könnte aber auch der Tag sein, an dem Du Dir endlich wieder erlaubst zu träumen und  Erfüllung in der Liebe wieder für möglich hältst. Du weißt selbst am besten, was auf Dich zutrifft.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[69]    = 'Skorpion - Schütze: die schwarze Messe';
cardv[69]    = '17';
cardn[69]    = '69';
ctext[69]    = new Array(1);
ctext[69][0] = '[Text not found!]';
ctext[69][1] = 'Es gibt keine Karte -und sieht sie auch noch so düster aus- die etwas Schlimmes verheisst. Auch die „Schwarze Messe“ ist nur eines von vielen Themen, die bearbeitet werden wollen. Allerdings braucht es einen klaren Blick und ein waches Bewusstsein um der heutigen Aufgabe gerecht zu werden: Du hast Dich in irgend eine Einsicht verrannt, bzw. Du hältst etwas für eine Erkenntnis, für eine Wahrheit ohne zu spüren, dass es sich dabei um eine fremde Idee handelt von der Du Dich hast verführen lassen. Diese „Idee“ birgt nicht viel Lebendiges, nicht viel Entwicklungsträchtiges in sich. Beobachte heute gut und Du wirst sehen: der „Spuk“, die Stagnation verschwindet von alleine.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[70]    = 'Skorpion - Steinbock: die Depression';
cardv[70]    = '18';
cardn[70]    = '70';
ctext[70]    = new Array(1);
ctext[70][0] = '[Text not found!]';
ctext[70][1] = 'Weitergehen! Nicht sitzen bleiben! Der zweite Name dieser Karte ist: Der Schemel des Vergessens. Du hast einen intensiven Entwicklungsprozess hinter Dir und bist jetzt etwas müde geworden. Alte Strukturen sind dabei sich aufzulösen, Du bist dabei Dich zu verändern. Gib jetzt nicht auf. Heute ist kein Tag zum Ausruhen oder gar zu resignieren. Mach einfach weiter wie bisher, Du bist auf dem richtigen Weg, auch wenn Dir heute alles dunkel und sinnlos erscheint. Am heutigen Tag entscheidet sich, wie Du in Zukunft mit schwierigen Zeiten umgehen wirst: hilflos ausgeliefert oder kraftvoll im Vertrauen.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[71]    = 'Skorpion - Wassermann: der Phönix';
cardv[71]    = '19';
cardn[71]    = '71';
ctext[71]    = new Array(1);
ctext[71][0] = '[Text not found!]';
ctext[71][1] = 'Im Moment (nicht nur heute) bist Du in einem grossen Wandlungsprozess. Alte Vorstellungen und Denkmuster haben sich überholt. Deine Lebenssituation will sich erneuern und Vieles muss dafür „sterben“. Wenn Du wie Phönix aus der Asche auferstehen möchtest, so musst du bereit sein vieles von dem, was Dir mal lieb und teuer war loszulassen. Was könnte das heute sein? Wo bist Du noch gefangen? Es bringt Dir nichts, Dich dem Wandel entgegenzustellen. Es geschieht sowie so was geschehen muss und Du verlierst durch Widerstand jene Seelen-Kraft, die der bunte Vogel braucht um in die Höhen der Freiheit aufzusteigen.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[72]    = 'Skorpion - Fische: der Heiligenschein';
cardv[72]    = '20';
cardn[72]    = '72';
ctext[72]    = new Array(1);
ctext[72][0] = '[Text not found!]';
ctext[72][1] = 'Oder auch: Die Scheinheiligkeit<br />Es gibt nichts Helles ohne Schatten, ohne dunkle Seite. Und natürlich gibt es –sei Dank- auch nichts Dunkles ohne lichte Kehrseite. Heute ist es für Dich wichtig diese Wahrheit, die Du längst kennst, auch wirklich anzuwenden. Dein Blick soll weit werden und beide Seiten mit einbeziehen. Mach Dir nicht vor, dass das, um was es geht ganz „heil“ ist. Es könnte sich herausstellen, dass der Schein trügt. Verfange Dich allerdings auch nicht im Negativen, denn auch hier würdest Du Dir etwas vormachen und ebenso einer Verführung auf den Leim gehen. Es gibt auf beiden Seiten „Karotten“, denen man nachlaufen kann.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[73]    = 'Schütze - Steinbock: die Beichte';
cardv[73]    = '19';
cardn[73]    = '73';
ctext[73]    = new Array(1);
ctext[73][0] = '[Text not found!]';
ctext[73][1] = 'Es geht heute um ein Eingeständnis, um Wahrheit, um seelische Wirklichkeit, DEINE Wirklichkeit.<br />Auch wenn die Karte an die Kirche erinnert, so hat das Ganze nichts mit Moral, mit Sünde oder Schuld zu tun. Die Beichte, die Du heute abzulegen hast hat nur und ausschliesslich mit Deinem Schicksal, mit Deinem persönlichen Gesetz zu tun. Tief in Deinem Inneren weißt Du um was es geht, Du musst es nur noch ins Bewusstsein holen. Auch wenn es weh tut, Du bist von Deinem Weg abgewichen und es wird Zeit zurückzukehren.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[74]    = 'Schütze - Wassermann: der Quanten-Sprung';
cardv[74]    = '20';
cardn[74]    = '74';
ctext[74]    = new Array(1);
ctext[74][0] = '[Text not found!]';
ctext[74][1] = 'Du wirst heute viel Neues erfahren. Das Alte liegt hinter Dir und das Neue direkt vor Dir. In einem Lebensbereich findest Du einen Sinn, der sich gravierend vom alten unterscheidet. Vielleicht begegnest Du Menschen, die Dir eine Richtung aufzeigen, die Du noch nicht kennst. Vielleicht erreichen Dich von irgendwo her „Botschaften“, die in Dir etwas auslösen, was eine Entwicklung in Gang bringt, mit der Du nicht gerechnet hast. Auf jeden Fall wartet ein spannender Tag auf Dich. Sei offen und wachsam, damit Du nichts verpasst!<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[75]    = 'Schütze - Fische: die Pythia';
cardv[75]    = '21';
cardn[75]    = '75';
ctext[75]    = new Array(1);
ctext[75][0] = '[Text not found!]';
ctext[75][1] = 'Das Leben gibt Dir Rätsel auf, sinnvolle Rätsel, die Du heute beachten und lösen sollst. Rätsel dieser Art (von Pythia, der Orakelpriesterin selbst gesandt) sind spirituelle Geschenke an Deine Seele. Meist spricht sie in Symbolen und Bildern, sodass der Mensch lernt diese zu übersetzen und auf sein Inneres zu hören. Vertraue heute Deiner Intuition, Deinen Träumen und Deiner inneren Weisheit. Nutze alles, was du heute erfährst als Brücke zur Wahrheit.<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[76]    = 'Steinbock - Wassermann: die Gefangenschaft';
cardv[76]    = '21';
cardn[76]    = '76';
ctext[76]    = new Array(1);
ctext[76][0] = '[Text not found!]';
ctext[76][1] = 'Du möchtest Dich verändern, an einem anderen Ort sein? Du glaubst eine Entscheidung zwischen Verantwortung und Freiheit treffen zu müssen. Niemand vermag eine derartige Wahl zu treffen. Die beiden grossen Themen der Menschheit sind Abfolge einer Entwicklung und werden dem Menschen nicht zur Auswahl vorgelegt. Du kannst also aufhören zu grübeln, eine Lösung ist mit Nachdenken nicht zu erzielen. Du bist (wie wir alle) der „geworfenen Stein“ und nur auf der  festgelegten „Flugbahn“ kannst Du frei werden. Wenn Du möchtest schon heute!<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[77]    = 'Steinbock - Fische: die Moira';
cardv[77]    = '22';
cardn[77]    = '77';
ctext[77]    = new Array(1);
ctext[77][0] = '[Text not found!]';
ctext[77][1] = 'Versöhne Dich mit Deinem Schicksal. Oder wenigstens mit diesem Tag. Du stehst vor einer inneren Entscheidung um die Du sehr ringen musst. Es gibt zwei Wege, mit anstehenden Problemen und Aufgaben umzugehen. Der eine beinhaltet die Versöhnung mit den Lebensumständen, der andere zeigt Abweisung und Verhärtung. Auf welchem Weg wirst Du wohl glücklicher?<div class="common_author">&copy; Hannelore Dörfler</div>';
titel[78]    = 'Wassermann - Fische: die Grals-Frage';
cardv[78]    = '23';
cardn[78]    = '78';
ctext[78]    = new Array(1);
ctext[78][0] = '[Text not found!]';
ctext[78][1] = 'Diese Karte wird sehr selten als Tageskarte gezogen. Also muss dies ein sehr bedeutsamer Tag für Dich sein., Wenn Du den Mut entwickelst Fragen (an das Leben) zu stellen, die letztlich nicht zu beantworten sind, kann heute für Dich ein Weg voller Zuversicht und Gelassenheit beginnen. Alleine die richtigen Fragen bringen Dich weiter! Antworten dienen der vorübergehenden Beruhigung des Intellektes und sind, kaum sind sie gedacht oder gehört schon der Vergangenheit an. Mit der richtigen Frage kommst Du in der Gegenwart, bei Dir selbst an.<div class="common_author">&copy; Hannelore Dörfler</div>';
var form_element        = 'tarot_input_form';
var layer_tutorial      = 'tarot_tutorial';
var layer_input         = 'tarot_input_reading';
var layer_export        = 'tarot_input_export';
var layer_readings      = 'tarot_readings';
var spreading           = 'Viertelkreis LT';
var spreading_offset_x  = 0;
var spreading_offset_y  = 75;
var spreading_height    = 300;
var spreading_width     = 0;
var spreading_width_c   = 75;
var spreading_spacer    = 6;
var spreading_max_cards = 1;
var spreading_repeats   = 1;
var spreading_cards     = new Array();
var spreading_from      = new Array();
var spreading_to        = new Array();
	spreading_cards[1]  = 1; spreading_from[1] = 1; spreading_to[1] = 78;
var spreading_rounds    = 1;
var spreading_target_x  = 0;
var spreading_target_y  = 0;
var deck_max_cards      = 78;
var deck_firstcard      = 1;
var deck_qe_max         = 12;
var deck_qe_double      = false;
var deck_path           = 'images/';
var deck_ext            = 'jpg';
var cards_height        = 119;
var cards_width         = 200;
var reading_show        = 'text';
var reading_title       = true;
var export_option       = false;
var tutorial_form       = true;
var tutorial_spread     = true;
var tutorial_reading    = true;
var reload_form         = false;
var reload_spread       = false;
var reload_reading      = false;
var txt_singular        = '';
var txt_plural          = 'n';
var txt_intro           = '<b>Ziehen Sie bitte 1 Karte</b>, indem Sie mit dem Mauszeiger darauf klicken.';
var txt_continue1       = 'Ziehen Sie bitte noch <b>';
var txt_continue2       = ' Karte';
var txt_continue3       = '</b>, indem Sie mit dem Mauszeiger darauf klicken.';
var txt_meaning1        = '';
var txt_meaning2        = '';

if ( screen.width < 1024 ) {
	for (i = 0; i <= deck_max_cards; i++) {
		document.images['img'+i].src='back.gif';
	}
}